### ISSUE TITLE
[Feature] Comment Embeds

### ISSUE THREAD

**Issue by belg1o** [MinnDevelopment/fxreddit#25] opened 2023-10-04 21:10 UTC
It'd be nice if it was able to grab the comments data from the URL, instead of linking the main post contents (in the case of copying a comment URL)

**Comment by MinnDevelopment** [comment] 2023-10-09 18:47
It currently shows the comment text content in the embed, is that not sufficient?

**Comment by belg1o** [comment] 2023-10-09 18:50
> It currently shows the comment text content in the embed, is that not sufficient?

It keeps posting the video/clip of the main post whenever I tried to do this. 

Eg. 
https://www.rxddit.com/r/GlobalOffensive/comments/16w33pp/comment/k2uobd2/?context=3
<img width="631" alt="image" src="https://github.com/MinnDevelopment/fxreddit/assets/11260048/02aa470b-e8f6-4002-b5b5-cb3a7edb2b63">

comment it's linked to 
<img width="642" alt="image" src="https://github.com/MinnDevelopment/fxreddit/assets/11260048/dfe2400f-102c-4eaf-9ba1-df10ebafac3b">

**Comment by MinnDevelopment** [comment] 2023-10-09 18:57
That's a discord issue, closing this as duplicate of #26

**Closed** 2023-10-09 18:57 UTC
